### ISSUE TITLE
Not processing jobs enqueued from another job

### ISSUE THREAD

**Issue by mkluczny** [brainopia/sidekiq-limit_fetch#51]
My problem is that some jobs are enqueued and never processed. I am able to reproduce this problem with the following setup:

```
:concurrency: 3
:queues:
  - a_queue
  - b_queue
  - c_queue
:limits:
    a_queue: 1
    b_queue: 1
    c_queue: 1
```

and jobs:

```
class AJob
  include Sidekiq::Worker

  sidekiq_options :queue => :a_queue, :retry => false

  def perform
    puts 'PERFORMING JOB A'
    sleep(rand(10))
    BJob.perform_async
    puts 'FINISHED JOB A'
  end
end
```
```
class BJob
  include Sidekiq::Worker

  sidekiq_options :queue => :b_queue, :retry => false

  def perform
    puts 'PERFORMING JOB B'
    sleep(rand(10))
    CJob.perform_async
    puts 'FINISHED JOB B'
  end
end
```
```
class CJob
  include Sidekiq::Worker

  sidekiq_options :queue => :c_queue, :retry => false

  def perform
    puts 'PERFORMING JOB C'
    sleep(rand(10))
    puts 'FINISHED JOB C'
  end
end
```

I run:
`AJob.perform_async`

and sidekiq log:
```
2015-02-10T14:14:54.277Z 25577 TID-owz3fuf4w AJob JID-deab0799a7c2563a6e2c7f93 INFO: start
PERFORMING JOB A
FINISHED JOB A
2015-02-10T14:14:56.282Z 25577 TID-owz3fuf4w AJob JID-deab0799a7c2563a6e2c7f93 INFO: done: 2.005 sec
```

BJob is enqueued but never processed

**Comment by jasoncox** [comment]
Looks the same as my problem #50

**Comment by klacointe** [comment]
Same problem here, but works downgrading sidekiq to 3.2.6

**Comment by cblavier** [comment]
Found any workaround ?

**Comment by brainopia** [comment]
@mkluczny - thank you for reproducing the problem
@klacointe - thank you for the tip about sidekiq version

I've released a new version with a fix. Could you please try it out?
It should work although slower than previous version because new sidekiq depends on newer celluloid which has broken an optimization of ours: 541fad464e6d9b1ddaa3f048f211e0196db8afca

**Comment by mkluczny** [comment]
Works fine, @brainopia many thanks for your support!

**Comment by klacointe** [comment]
:ok_hand:
