### ISSUE TITLE
Limit being ignored

### ISSUE THREAD

**Issue by kryachkov** [brainopia/sidekiq-limit_fetch#52]
sidekiq 3.3.2
sidekiq-limit_fetch 2.3.0

I put `Sidekiq::Queue['some_queue'].limit = 1` in `config/initializers/sidekiq.rb`. Then I start rails console (sidekiq is not started) and do this in console:

    2.1.2 :001 > Sidekiq::Queue.new('future_trades').limit
     => 1

Then I start sidekiq, and after sidekiq has successfully started I get

    2.1.2 :001 > Sidekiq::Queue.new('future_trades').limit
     => nil

And limit is being totally ignored

**Comment by brainopia** [comment]
Limits are reset during deploy to the state of sidekiq.yml. It's done so removal of limit from sidekiq.yml would work.

I've added a check to keep dynamic limits that has been set in initializers.

**Comment by kryachkov** [comment]
:+1:

**Comment by kryachkov** [comment]
Is there any way to not require Redis connection when setting `Sidekiq::Queue['some_queue'].limit = 1`?When this is put into initializer and when there is no Redis connection even `rake db:migrate` can not be performed

**Comment by brainopia** [comment]
You can wrap it in rescue since it's unusual to ignore attempt to complete command.
Or you can move limit from initializer to config/sidekiq.yml :)
