### ISSUE TITLE
Sidekiq suddenly quitting and not processing any enqueued jobs

### ISSUE THREAD

**Issue by johnmcauley** [brainopia/sidekiq-limit_fetch#58]
Hello,
Using:

sidekiq-failures (0.4.4)
sidekiq-limit_fetch (2.4.2)
sidekiq (>= 2.6.5, < 4.0)

I am using Limit Fetch and it's great but I have tow recurring issues:

1. Suddenly all queues are stopped and now new jobs are processed - rather a biggy.
2. Limit does not always respect the concurrency setting.

Any ideas?

Thanks,

j

**Comment by brainopia** [comment]
@johnmcauley Hello,

Can you show me sidekiq.yml config? And give me an the result of `puts Sidekiq::Queue['foobar'].explain, Sidekiq::Queue['foobar'].size` (`foobar` is the name of the queue where and when jobs aren't processed correctly).

**Comment by brainopia** [comment]
Please reopen this issue with additional information :+1:
