### ISSUE TITLE
evalsha command is locking our Redis

### ISSUE THREAD

**Issue by djpate** [brainopia/sidekiq-limit_fetch#61]
We are noticing a low latency on one of our Redis server.

We narrowed it down to this evalsha command that seems to be made by this gem.

"evalsha" "7b91ed9f4cba40689cea7172d1fd3e08b2efd8c9" "0" "sidekiq:" "12476987-d704-408c-9a1a-b2c215b0545a" "foo" "bar" "baz" ....

This command seems to take about 4 seconds. The same code on production works fine so I don't know what to think.

Any idea on how to debug this?

**Comment by brainopia** [comment]
Woah, 4 seconds is a lot.

Can you tell me how many queues do you have and show me the sidekiq-limit_fetch config.

**Comment by djpate** [comment]
We have around 150 queues.

I've "fixed" the issue on staging by droping all the jobs on our queues (~ 10M). Since then it went back to normal. 

We do have about 10M jobs on production and it's running without any issues so maybe our redis instance on staging is not powerful enough but I checked that it was not swaping.

Not sure what do you need as for sidekiq limit fetch config.

**Comment by brainopia** [comment]
If you use process_limits then it would add one more redis call. But aside from that you have quite a lot of queues, you'd need indeed a powerful redis instance to handle that.

In a distant future I hope to rewrite our current implementation not to use redis at all to handle limit distribution between sidekiq processors :)
