### ISSUE TITLE
Set dynamic queue priority

### ISSUE THREAD

**Issue by akshayrawat** [brainopia/sidekiq-limit_fetch#64]
Currently dynamic queues have lowest priority. Is it possible to set a specific priority to all dynamic queues? My use case needs the dynamic queue to have the highest priority.

**Comment by brainopia** [comment]
@akshayrawat do you have weighted or strict queues?
The priority of weighted queue is defined by how many times it's present in an array: `Sidekiq::LimitFetch::Queues.instance_variable_get(:@queues)`.
The priority of strict queue is defined by its position in the same array.

Dynamic queues are pushed just once to the end of this array.
To increase its priority in weighted scenario you'll need to push it a few more times to get appropriate balance. To increase its priority in strict scenario you'll need to move it to the beginning of array.
