### ISSUE TITLE
Thread.exclusive is deprecated since Ruby 2.3.0

### ISSUE THREAD

**Issue by rosenfeld** [brainopia/sidekiq-limit_fetch#65]
I get this warning message:

"Thread.exclusive is deprecated, use MutexThread.exclusive is deprecated, use Mutex"

**Comment by knightq** [comment]
:+1:

**Comment by krzysiek1507** [comment]
@rosenfeld #66

**Comment by brainopia** [comment]
Thank you, #66 was merged.
