### ISSUE TITLE
Feature Request: Process newest/latest job in queue

### ISSUE THREAD

**Issue by xanview** [brainopia/sidekiq-limit_fetch#86]
Any way to tell Sidekiq to always process the newest/latest job in a specific queue? -- I have a specific queue which needs to always do the newest job and catch up on older ones later in the day. Any way to achieve that?

**Comment by Yoshyn** [comment]
Your question is not related to sidekiq-fetch-limit but relative to sidekiq : https://github.com/mperham/sidekiq

You should better close this issue and repost in the right place if you want an answer.

But at my knowledge sidekiq is Last in, Last out per queue.
However you can play with the queue name and create priority for some queue.

You can see other extensions here (and maybe find something that fit you) : 
https://github.com/mperham/sidekiq/wiki/Delayed-extensions

**Comment by xanview** [comment]
Yes, I'm trying to find a way to make a specific queue Last in, First out. For example:

```
item1 -> queue1
item2 -> queue1
item3 -> queue1
sidekiq <- item3
item4 -> queue1
item5 -> queue1
sidekiq <- item5
sidekiq <- item4
sidekiq <- item2
sidekiq <- item1
```

Not quite sure how playing with queue names/priorities will help achieve that, delayed extensions don't seem relevant either. I'll try asking on the sidekiq project issues.
